### PR TITLE
Data class

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by thewtex** [comment]
Re: #7 

@TomNicholas interested in your thoughts. Ideally, some dims would be optional. A 3D image with one plane is different in type from a 2D image. I am not sure how we do that here, though. Ideally `z: Optional[Coord[Literal['z'], np.float64]`, but would that work with xarray-dataclasses?

**Comment by thewtex** [comment]
> I am not sure how we do that here, though.

After further thought, dimension-specific dataclasses makes sense.

**Comment by thewtex** [comment]
@TomNicholas @astropenguin I am running into https://github.com/astropenguin/xarray-dataclasses/issues/104 (Python 3.10 support) -- what is holding this back?

**Comment by TomNicholas** [comment]
Hi @thewtex - sorry - I am following this (and excited to see how it can be done), but I'm not actually closely familiar with the internals of xarray-dataclasses, it just seemed like an obvious place to start. Happy to discuss the interaction with datatree / learn more though.

**Pull request merged**
